### ISSUE TITLE
Where can I get the dataset?

### ISSUE THREAD

**Issue by TNemes-3141** [samuelyu2002/pedestrian-traffic-lights#3]
Hello,
For this kind of application, I have searched for a long while and the implementation is very good! Now, the Pedestrian-Traffic-Light (PTL)-dataset you mention in the Readme is not in the repository and I also can't find it anywhere else on the internet. I'd like to train some other models with it to see how it performs.
Can you please tell me how to get the images of the dataset? Thanks!

**Comment by samuelyu2002** [comment]
Check the section titles Download in the readme. There are 3 sizes of the dataset available, you can download any of the three by clicking on the hyperlinks.
