### ISSUE TITLE
How to use your model for real time image 

### ISSUE THREAD

**Issue by jonylu7** [samuelyu2002/pedestrian-traffic-lights#4]
Hi guys! First of all, Amazing work! I am currently working on a project that used Jetson nano and CSI camera. It's a  detector meant to help visually impaired person. I am currently trying your model but I am troubling making it to read real time footage . Can you guys tell me what to search for or what to learn? Thanks!

**Comment by samuelyu2002** [comment]
Do you have PyTorch installed on the Jetson nano? If not, you can try using this link https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-7-0-now-available/72048. (or you can search something like run pytorch model on jetson nano). 

This tutorial might also help with implementing a real time camera feed https://news.developer.nvidia.com/realtime-object-detection-in-10-lines-of-python-on-jetson-nano/.
