### ISSUE TITLE
LYTNETV2 not working, while LYTNET yes

### ISSUE THREAD

**Issue by marcoleino** [samuelyu2002/pedestrian-traffic-lights#5]
With the same files, the training.py crashes only when uses LytnetV2, with the following error:

    RuntimeError: Given input size: (960x9x12). Calculated output size: (960x0x1). Output size is too small

**Comment by samuelyu2002** [comment]
Can you try changing line 153 of lytnetv2.py to "self.features.append(nn.AvgPool2d(9,12))" or "self.features.append(nn.AdaptiveAvgPool2d((1,1))"

**Comment by marcoleino** [comment]
thank you, the two trainings have started in parallel with both options. I will write here which one will achieve the best performance and accuracy
